[package]
name = "ejscv"
version = "0.0.2"
entrypoint = "src/lib.typ"
authors = ["ejsdotsh"]
license = "Apache2.0"
description = "EJ's CV template"
repository = "https://github.com/ejsdotsh/ejscv"
keywords = ["cv", "resume"]
categories = ["cv"]
disciplines = []
compiler = "0.13.0"
exclude = [
  "docs/",
  "tests/",
  ".git",
  ".gitignore",
  ".github",
  ".vscode",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
