[package]
name = "ejscv"
version = "0.0.2"
entrypoint = "ejscv.typ"
authors = ["ejsdotsh"]
license = "Apache2.0"
description = "EJ's CV template using Typst and YAML"
repository = "https://github.com/ejsdotsh/ejscv"
keywords = ["CV", "curriculum vitae", "resume", "YAML", "minimalistic"]
categories = ["cv"]
disciplines = []
compiler = "0.13.0"
exclude = [
  "docs/",
  "tests/",
  ".git",
  ".gitignore",
  ".github",
  ".vscode",
]

[template]
path = "template"
entrypoint = "template.typ"
thumbnail = "examples/thumbnail1.png"
